# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
git:
  depth: 150

matrix:
  include:
    - os: linux
      dist: trusty
      r: devel

    - os: linux
      dist: trusty
      r: release

    - os: linux
      r: oldrel

    - os: osx
      r: release

    - os: osx
      r: oldrel

    - os: osx
      r: devel

  allow_failures:
    - os: linux
      dist: trusty
      r: devel

    - os: osx
      r: devel

addons:
  apt:
    packages:
      - libxml2-dev
      - libpq-dev
r_check_revdep: false
warnings_are_errors: false
