language: r
cache: packages
sudo: false
matrix:
  include:
    - os: linux
      dist: precise
      r: release
    - os: linux
      dist: precise
      r: devel

    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r: release
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r: devel

    - os: osx
      osx_image: xcode8.1
      r: release

    - os: osx
      r: release

addons:
  apt:
    packages:
      - libxml2-dev
      - libpq-dev
r_check_revdep: false
warnings_are_errors: false
