language: r
<<<<<<< HEAD
=======
sudo: false
>>>>>>> master
r:
  - oldrel
  - release
  - devel
cache: packages
addons:
  apt:
    packages:
      - libxml2-dev
      - libpq-dev
r_check_revdep: true
